apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hosting-deployment
  labels:
    app: hosting-node
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hosting-node
    spec:
      containers:
      - name: hosting-node
        image: gcr.io/inspiring-folio-200821/hosting_test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081

